version: '3'
services:
  s_ota:
    container_name: s_ota
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /storages/firmware:/firmware
    ports:
      - "8079:8079"
